const { hasAdminPerms, isTopAdmin, getRoleLevel } = require("./roles");

const PERMISSIONS = {
  MANAGE_BOT: "manage_bot",
  MANAGE_DEFCON: "manage_defcon",
  MANAGE_CITIES: "manage_cities",
  MANAGE_USERS: "manage_users",
  MANAGE_TICKETS: "manage_tickets",
  MODERATE_INTERNAL: "moderate_internal",
  MODERATE_EXTERNAL: "moderate_external",
  MANAGE_SERVICE: "manage_service",
  VIEW_STATS: "view_stats",
  USE_BOT: "use_bot",
};

const ROLE_PERMISSIONS = {
  AGENT_JUNIOR: [PERMISSIONS.USE_BOT],
  AGENT: [PERMISSIONS.USE_BOT, PERMISSIONS.VIEW_STATS],
  AGENT_EXPERIENCED: [PERMISSIONS.USE_BOT, PERMISSIONS.VIEW_STATS],
  STAGIAIRE: [PERMISSIONS.USE_BOT, PERMISSIONS.VIEW_STATS],
  SUPERVISEUR: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MODERATE_EXTERNAL,
    PERMISSIONS.MANAGE_SERVICE,
    PERMISSIONS.MANAGE_TICKETS,
  ],
  SECRETAIRE: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.MANAGE_USERS,
  ],
  MANAGER: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MODERATE_EXTERNAL,
    PERMISSIONS.MANAGE_SERVICE,
    PERMISSIONS.MANAGE_TICKETS,
  ],
  CO_FONDATEUR: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MODERATE_EXTERNAL,
    PERMISSIONS.MANAGE_SERVICE,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.MANAGE_DEFCON,
    PERMISSIONS.MANAGE_CITIES,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_BOT,
  ],
  PDG: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MODERATE_EXTERNAL,
    PERMISSIONS.MANAGE_SERVICE,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.MANAGE_DEFCON,
    PERMISSIONS.MANAGE_CITIES,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_BOT,
  ],
  ADMIN: [
    PERMISSIONS.USE_BOT,
    PERMISSIONS.VIEW_STATS,
    PERMISSIONS.MODERATE_INTERNAL,
    PERMISSIONS.MODERATE_EXTERNAL,
    PERMISSIONS.MANAGE_SERVICE,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.MANAGE_DEFCON,
    PERMISSIONS.MANAGE_CITIES,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_BOT,
  ],
};

function getUserPermissions(roleId) {
  return ROLE_PERMISSIONS[roleId] || [PERMISSIONS.USE_BOT];
}

function hasPermission(roleId, permission) {
  const perms = getUserPermissions(roleId);
  return perms.includes(permission);
}

function hasAnyPermission(roleId, ...permissions) {
  return permissions.some((p) => hasPermission(roleId, p));
}

function hasAllPermissions(roleId, ...permissions) {
  return permissions.every((p) => hasPermission(roleId, p));
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getUserPermissions,
  hasPermission,
  hasAnyPermission,
  hasAllPermissions,
};
